### ISSUE TITLE
init_log is called while internet connection is unavailable

### ISSUE THREAD

**Issue by soimkim** [fosslight/fosslight_util#27]
When init_log is called while internet connection is unavailable, if the package version cannot be checked from pypi, does it only output an info message and operate without errors?

**Comment by soimkim** [comment]
```
Traceback (most recent call last):
  File "/Users/so-imkim/opt/anaconda3/bin/fosslight_source", line 8, in <module>
    sys.exit(main())
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/fosslight_source/run_scancode.py", line 56, in main
    run_scan(path_to_scan, output_file, write_json_file, -1, False, print_matched_text)
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/fosslight_source/run_scancode.py", line 81, in run_scan
    logger, _result_log = init_log(os.path.join(output_dir, "fosslight_src_log_"+start_time+".txt"),
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/fosslight_util/set_log.py", line 64, in init_log
    init_check_latest_version(pkg_version, main_package_name)
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/fosslight_util/set_log.py", line 22, in init_check_latest_version
    has_update = lastversion.has_update(repo=main_package_name, at='pip', current_version=pkg_version)
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/lastversion/lastversion.py", line 232, in has_update
    latest_version = latest(repo, output_format='version', pre_ok=pre_ok, at=at)
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/lastversion/lastversion.py", line 141, in latest
    project_holder = HolderFactory.HOLDERS[at](repo, hostname=None)
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/lastversion/PypiRepoSession.py", line 37, in __init__
    self.project = self.get_project()
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/lastversion/PypiRepoSession.py", line 25, in get_project
    r = self.get(url)
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/so-imkim/opt/anaconda3/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/fosslight_source/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffce3871850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

```
